spring:
  application:
    # ????
    name: KafkaEasyStudy02
    # kafka????(ip+??)
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    # ?????
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.ToStringSerializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto-offset-reset: earliest
#      max-poll-records: 20
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto-offset-reset: latest
      auto-offset-reset: earliest

#    listener:
#      # 开启消息监听的手动确认模式
#      ack-mode: manual
#      type: batch


    # 配置模版默认的主题topic名称
#    template:
#      default-topic: default-topic

kafka:
  topic:
    name: helloTopic
  consumer:
    group: helloGroup

